version: '3'

services:

  db:
    image: 'mysql:latest'
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=qlsv
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    ports:
      - 33061:3306

  web:
    image: 'dmhieu/qlsv-spring-api:latest'
    container_name: springboot
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8086:8086
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=qlsv
      - DATABASE_PORT=33061
  ui:
    image: 'dmhieu/qlsv-frontend-angular:latest'
    container_name: angular
    ports:
      - 4200:80