version: '3'

services:

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=qlsv
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    ports:
      - 33061:3306

  web:
    image: qlsv-mysql
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8086:8086
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=qlsv
      - DATABASE_PORT=33061
  ui:
    image: webui
    ports:
      - 4200:80